# Recallo — Justfile
# Run `just <recipe>` to execute. Requires just (https://github.com/casey/just)
# and the Dioxus CLI (dx) installed.

# Android environment — adjust paths if needed
export JAVA_HOME := "/usr/lib/jvm/java-25-openjdk"
export ANDROID_HOME := "/opt/android-sdk"
export NDK_HOME := "/opt/android-sdk/ndk/27.0.12077973"

# Package name as generated by dx (com.example.<AppName>)
APP_PACKAGE := "com.example.Recallo"
APK_DEBUG := "target/dx/recallo/debug/android/app/app/build/outputs/apk/debug/app-debug.apk"
APK_RELEASE := "target/dx/recallo/release/android/app/app/build/outputs/apk/debug/app-debug.apk"

# Default recipe: show available commands
default:
    @just --list

# ── Development ──────────────────────────────────────────────────────────────

# Run on a connected Android device or emulator (hot-reload)
run:
    dx serve --platform android --target aarch64-linux-android

# Run as a desktop app for quick iteration (no Android needed)
run-desktop:
    dx serve --platform desktop

# ── Quality ──────────────────────────────────────────────────────────────────

# Run all lints (rustfmt check + clippy)
lint:
    cargo fmt --check
    cargo clippy -- -D warnings

# Auto-format the code
fmt:
    cargo fmt

# ── Build ─────────────────────────────────────────────────────────────────────

# Build debug APK for ARM64 (physical device) with patches (icons, SDK, alignment)
build:
    dx build --platform android --target aarch64-linux-android
    ./scripts/android-patch.sh debug

# Build release APK for ARM64 with patches
build-release:
    dx build --platform android --target aarch64-linux-android --release
    ./scripts/android-patch.sh release

# ── Device ───────────────────────────────────────────────────────────────────

# Build + install debug APK on connected device
install: build
    $ANDROID_HOME/platform-tools/adb install -r --bypass-low-target-sdk-block {{APK_DEBUG}}

# Build + install release APK on connected device
install-release: build-release
    $ANDROID_HOME/platform-tools/adb install -r --bypass-low-target-sdk-block {{APK_RELEASE}}

# Install without rebuilding (uses existing APK)
install-only:
    $ANDROID_HOME/platform-tools/adb install -r --bypass-low-target-sdk-block {{APK_DEBUG}}

# Install and launch the app immediately
install-launch: install
    $ANDROID_HOME/platform-tools/adb shell monkey -p {{APP_PACKAGE}} 1

# Launch already-installed app
launch:
    $ANDROID_HOME/platform-tools/adb shell monkey -p {{APP_PACKAGE}} 1

# Show ADB logcat filtered to Recallo
logs:
    $ANDROID_HOME/platform-tools/adb logcat -s "RustStdoutStderr" "AndroidRuntime" "Recallo"

# List connected ADB devices
devices:
    $ANDROID_HOME/platform-tools/adb devices
