#!/usr/bin/env python3
"""Generate src/data/math_words.rs from temp_jsons/*.json files."""

import json
import os

JSONS_DIR = os.path.join(os.path.dirname(__file__), "..", "temp_jsons")

# Mapping: (predmet, otazka) -> (MathTopic variant, display_name, emoji)
TOPIC_MAP = {
    # Analysis topics
    ("analyza", 1): ("Matrices", "Matice", "🔢"),
    ("analyza", 2): ("Continuity", "Spojitost", "📈"),
    ("analyza", 3): ("Convergence", "Konvergence", "🎯"),
    ("analyza", 4): ("Derivatives", "Derivace", "📐"),
    ("analyza", 5): ("Integrals", "Integrály", "∫"),
    ("analyza", 6): ("Extrema", "Extrémy", "⛰️"),
    ("analyza", 7): ("Graphs", "Grafy", "📊"),
    ("analyza", 8): ("RandomVariableA", "Náhodná veličina", "🎲"),
    # DataScience/Statistics topics
    ("statistika", 1): ("Estimation", "Odhady", "📏"),
    ("statistika", 2): ("RelationshipAnalysis", "Analýza vztahů", "🔗"),
    ("statistika", 3): ("BayesianInference", "Bayesovská inference", "🧮"),
    ("statistika", 4): ("Classification", "Klasifikace", "🏷️"),
    ("statistika", 5): ("RegressionCorrelation", "Regrese a korelace", "📉"),
    ("statistika", 6): ("ExploratoryAnalysis", "Průzkumová analýza", "🔍"),
    ("statistika", 7): ("TimeSeries", "Časové řady", "⏰"),
    ("statistika", 8): ("SupervisedML", "Supervised ML", "🤖"),
}

SUBJECT_MAP = {
    "analyza": "Analysis",
    "statistika": "DataScience",
}


def escape_rust_string(s: str) -> str:
    """Escape a string for use in a Rust &'static str literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    entries = []

    for fname in sorted(os.listdir(JSONS_DIR)):
        if not fname.endswith(".json"):
            continue
        fpath = os.path.join(JSONS_DIR, fname)
        with open(fpath, "r", encoding="utf-8") as f:
            data = json.load(f)

        predmet = data["predmet"]
        otazka = data["otazka"]
        key = (predmet, otazka)

        if key not in TOPIC_MAP:
            print(f"WARNING: No mapping for {key} in {fname}, skipping")
            continue

        topic_variant, _, _ = TOPIC_MAP[key]
        subject_variant = SUBJECT_MAP[predmet]

        for item in data["polozky"]:
            nazev = item["nazev"]
            typ = item["typ"]
            zneni = item["zneni"]

            # Map typ to MathEntryType
            if typ in ("definice",):
                entry_type = "Definition"
            else:
                entry_type = "Theorem"

            entries.append((nazev, zneni, entry_type, subject_variant, topic_variant))

    # Generate Rust code
    lines = []
    lines.append("// Auto-generated from temp_jsons/ — do not edit manually.")
    lines.append("// Generated by scripts/generate_math_data.py")
    lines.append("")
    lines.append("use serde::{Deserialize, Serialize};")
    lines.append("")

    # MathSubject enum
    lines.append(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]"
    )
    lines.append("pub enum MathSubject {")
    lines.append("    Analysis,")
    lines.append("    DataScience,")
    lines.append("}")
    lines.append("")

    # MathEntryType enum
    lines.append(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]"
    )
    lines.append("pub enum MathEntryType {")
    lines.append("    Definition,")
    lines.append("    Theorem,")
    lines.append("}")
    lines.append("")
    lines.append("impl MathEntryType {")
    lines.append("    pub fn display_name(&self) -> &'static str {")
    lines.append("        match self {")
    lines.append('            MathEntryType::Definition => "Definice",')
    lines.append('            MathEntryType::Theorem => "Věta",')
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # MathTopic enum
    lines.append(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]"
    )
    lines.append("pub enum MathTopic {")
    # Collect unique topics in order
    seen_topics = []
    for _, _, _, _, topic in entries:
        if topic not in seen_topics:
            seen_topics.append(topic)
    for topic in seen_topics:
        lines.append(f"    {topic},")
    lines.append("}")
    lines.append("")

    # MathTopic impl
    lines.append("impl MathTopic {")

    # display_name
    lines.append("    pub fn display_name(&self) -> &'static str {")
    lines.append("        match self {")
    for key, (variant, display, _) in TOPIC_MAP.items():
        lines.append(f'            MathTopic::{variant} => "{display}",')
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    # emoji
    lines.append("    pub fn emoji(&self) -> &'static str {")
    lines.append("        match self {")
    for key, (variant, _, emoji) in TOPIC_MAP.items():
        lines.append(f'            MathTopic::{variant} => "{emoji}",')
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    # subject
    lines.append("    pub fn subject(&self) -> MathSubject {")
    lines.append("        match self {")
    for key, (variant, _, _) in TOPIC_MAP.items():
        predmet = key[0]
        subject = SUBJECT_MAP[predmet]
        lines.append(f"            MathTopic::{variant} => MathSubject::{subject},")
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    # key (for persistence)
    lines.append("    pub fn key(&self) -> &'static str {")
    lines.append("        match self {")
    for key, (variant, display, _) in TOPIC_MAP.items():
        key_str = variant.lower()
        lines.append(f'            MathTopic::{variant} => "{key_str}",')
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    # all_for_subject
    lines.append(
        "    pub fn all_for_subject(subject: MathSubject) -> &'static [MathTopic] {"
    )
    lines.append("        match subject {")

    analysis_topics = [v for (p, _), (v, _, _) in TOPIC_MAP.items() if p == "analyza"]
    ds_topics = [v for (p, _), (v, _, _) in TOPIC_MAP.items() if p == "statistika"]

    lines.append("            MathSubject::Analysis => &[")
    for t in analysis_topics:
        lines.append(f"                MathTopic::{t},")
    lines.append("            ],")
    lines.append("            MathSubject::DataScience => &[")
    for t in ds_topics:
        lines.append(f"                MathTopic::{t},")
    lines.append("            ],")
    lines.append("        }")
    lines.append("    }")

    lines.append("}")
    lines.append("")

    # MathEntry struct
    lines.append("#[derive(Debug, Clone, PartialEq, Eq)]")
    lines.append("pub struct MathEntry {")
    lines.append("    pub name: &'static str,")
    lines.append("    pub statement: &'static str,")
    lines.append("    pub entry_type: MathEntryType,")
    lines.append("    pub subject: MathSubject,")
    lines.append("    pub topic: MathTopic,")
    lines.append("}")
    lines.append("")

    # Static array
    lines.append(f"pub static MATH_ENTRIES: &[MathEntry] = &[")

    # Group by subject then topic for readability
    current_subject = None
    current_topic = None
    for nazev, zneni, entry_type, subject, topic in entries:
        if subject != current_subject:
            current_subject = subject
            lines.append(f"    // ── {subject.upper()} {'─' * 60}")
        if topic != current_topic:
            current_topic = topic
            display = [d for (v, d, _) in TOPIC_MAP.values() if v == topic][0]
            lines.append(f"    // ── {display} ──")

        nazev_escaped = escape_rust_string(nazev)
        zneni_escaped = escape_rust_string(zneni)
        lines.append(f"    MathEntry {{")
        lines.append(f'        name: "{nazev_escaped}",')
        lines.append(f'        statement: "{zneni_escaped}",')
        lines.append(f"        entry_type: MathEntryType::{entry_type},")
        lines.append(f"        subject: MathSubject::{subject},")
        lines.append(f"        topic: MathTopic::{topic},")
        lines.append(f"    }},")

    lines.append("];")
    lines.append("")

    output = "\n".join(lines)
    out_path = os.path.join(
        os.path.dirname(__file__), "..", "src", "data", "math_words.rs"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"Generated {out_path} with {len(entries)} entries")


if __name__ == "__main__":
    main()
